### ISSUE TITLE
many packages now signed

### ISSUE THREAD

**Issue by ghost** [eduvpn/eduvpn-debian#12]
Many of the packages are now available here: https://software.tuxed.net/. They are signed with my public PGP key: `6237 BAF1 418A 907D AA98  EAA7 9C5E DD64 5A57 1EB2`

**Comment by ghost** [comment]
the VPN components have releases (on GitHub) that contain the .tar.xz and .tar.xz.asc files now.

**Comment by joostvb-gh** [comment]
debian packages for

php-json-signer
php-oauth2-client
php-oauth2-server
php-openvpn-connection-manager
php-saml-ds
php-secookie
php-yubitwee

and

vpn-admin-portal
vpn-lib-common
vpn-server-api
vpn-server-node
vpn-user-portal

are now fixed (but not yet built).  See also issue #9  for details.

**Comment by ghost** [comment]
all these are now buildable with PGP check in stable branch.
