### ISSUE TITLE
package auth-script-openvpn

### ISSUE THREAD

**Issue by ghost** [eduvpn/eduvpn-debian#2]
* [x] use release from https://github.com/fkooman/auth-script-openvpn/releases
* [x] "merge" the meson build file upstream and put in the release tar (@fkooman)
* [x] test it to make sure it works (make sure eduVPN / Let's Connect! uses the plugin to validate 2FA credentials)

Initial work was done by @joostvb-gh [here](https://github.com/eduvpn/eduvpn-debian/tree/develop/openvpn-plugin-auth-script/debian).

**Comment by ghost** [comment]
See Fedora/CentOS package https://fkooman.fedorapeople.org/openvpn-plugin-auth-script/

**Comment by fkooman** [comment]
https://github.com/fac/auth-script-openvpn/pull/12

**Comment by joostvb-gh** [comment]
I plan to start working on debian packaging for this one soonish.

**Comment by fkooman** [comment]
A signed release is available now: https://github.com/fkooman/auth-script-openvpn/releases

**Comment by fkooman** [comment]
Some work is done here: https://github.com/eduvpn/eduvpn-debian/tree/master/openvpn-plugin-auth-script/debian by @joostvb-gh

**Comment by fkooman** [comment]
The package still needs to be updated to use the actual release.

**Comment by fkooman** [comment]
I tried to use it and build it, but doesn't work. The package naming is weird. So removed my work in the stable branch for now.

**Comment by fkooman** [comment]
* [ ] use release from https://github.com/fkooman/auth-script-openvpn/releases
* [ ] "merge" the meson build file upstream and put in the release tar (@fkooman)
* [ ] test it to make sure it works (make sure eduVPN / Let's Connect! uses the plugin to validate 2FA credentials)
