### ISSUE TITLE
don't ask to overwrite configuration files

### ISSUE THREAD

**Issue by ghost** [eduvpn/eduvpn-debian#3]
every config template upgrade asks the user to take the new configuration file. Doing so will break the installation. There is a guarantee that existing configuration files will keep working, so Debian shouldn't complain all the time!

**Comment by frozen-sky** [comment]
Files in /etc are by debian/dpkg seen as configuration files. If local changes are made, it will always ask to verify the changes.
I suggest to move the config file to config.php.example and add a post install script which copies this file over to config if it is non-existing. That way, there is always the bundeled reference.

Even nicer would be to move the config.php.example file to the docs/readme folders of the pacakge, however, I do not think the do exist currently. I can make a PR for this if you agree on this approach

**Comment by ghost** [comment]
> I suggest to move the config file to config.php.example and add a post install script which copies this file over to config if it is non-existing. That way, there is always the bundeled reference.

That sounds like a good idea! 

> Even nicer would be to move the config.php.example file to the docs/readme folders of the pacakge, however, I do not think the do exist currently. I can make a PR for this if you agree on this approach

This is already done, see e.g. `/usr/share/doc/vpn-user-portal`.

**Comment by ghost** [comment]
#6

**Comment by joostvb-gh** [comment]
it seems ucf is what you want here.  See https://manpages.debian.org/stretch/ucf/ucf.1.en.html .
Searching on https://codesearch.debian.net/ could help finding good usage examples.

**Comment by gijzelaerr** [comment]
or symlink to `/var`?

https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles

**Comment by joostvb-gh** [comment]
Symlinking to /var would be useful if we'd generate config files in postinst.  we currently don't do that.
we _do_ use debconf though.  @fkooman : which config file in which of our packages are we
talking about here?  do you have a specific example where dpkg is prompting the user while it
should not?

**Comment by ghost** [comment]
The `config.php` in `/etc/vpn-X/`.

**Comment by ghost** [comment]
The `config.php.example` file which is used to copy it to `/etc/vpn-X` is occasionally updated in non-breaking ways. So it doesn't need to merge the configuration or anything. On Fedora/CentOS this is solved by RPM automatically placing the `config.php` as a `config.php.rpmnew` file without asking questions. As the example config is also already in `/usr/share/doc/vpn-X/` that is also fine.

**Comment by joostvb-gh** [comment]
If you are sure you don't want the user / local admin ever to manually edit config.php, it should not
be in /etc but e.g. in /usr/lib/vpn-X : that would make it clear to the users they're not supposed to
edit it.  Maybe that could work?

**Comment by ghost** [comment]
Huh? Of course the admin modifies the configuration file(s)...

**Comment by joostvb-gh** [comment]
@fkooman explained me his reasoning out of band (on #eduvpn irc.freenode.net) .  I believe current behaviour is as expected on Debian systems: there is no big urgent problem here.  Later we could
add more porcelain by using ucf and/or more debconf.  Debian admins who prefer to allways keep
old configs can tell dpkg this by passing --force-confold (and are supposed to know about this).

Bottom line: this problem is not urgent.

**Comment by gijzelaerr** [comment]
you can get that behavior by configuring apt to be noninteractive, for example by `export DEBIAN_FRONTEND=noninteractive`

**Comment by ghost** [comment]
Not urgent, this is the Debian way.
