### ISSUE TITLE
package php-constant-time for Debian 10

### ISSUE THREAD

**Issue by ghost** [eduvpn/eduvpn-debian#52]
Debian 10 no longer has https://packages.debian.org/stretch/php-constant-time

**Comment by joostvb-gh** [comment]
See https://bugs.debian.org/892587 for background.  Indeed, it seems we should build the sources as in debian/sid now on 10/buster.  Or maybe the binary as shipped with debian/sid works OK for us as-is: I'll investigate.

**Comment by joostvb-gh** [comment]
first preliminary results seem to indicate indeed php-constant-time_2.2.3-1_all.deb as now shipped with sid works fine on buster.  will do more research and propose solution.

**Comment by ghost** [comment]
https://packages.debian.org/sid/php-constant-time

we could just add this package to our repo as well...

**Comment by ghost** [comment]
https://github.com/eduvpn/eduvpn-debian/commit/4a3fe9c486d724a8c24850f611b1eac474035a59
