### ISSUE TITLE
package vpn-ca

### ISSUE THREAD

**Issue by ghost** [eduvpn/eduvpn-debian#54]
https://github.com/fkooman/vpn-ca

**Comment by ghost** [comment]
(Signed) source packages here: https://software.tuxed.net/vpn-ca/download.html

**Comment by joostvb-gh** [comment]
vpn-ca with

vpn-ca (1.0.0-1) stable; urgency=medium
 -- François Kooman <fkooman@tuxed.net>  Wed, 20 Nov 2019 11:58:00 +0100

and

vpn-ca (0.0.7-2) unstable; urgency=medium
 -- Joost van Baal-Ilić <joostvb-eduvpn@ad1810.com>  Wed, 20 Nov 2019 10:08:08 +0100

is in eduvpn-debian branch buster.

i guess this issue can be closed?

**Comment by ghost** [comment]
RPM spec: https://git.tuxed.net/rpm/vpn-ca/tree/SPECS/vpn-ca.spec

**Comment by ghost** [comment]
Packaged now for stretch, works like a charm: https://github.com/eduvpn/eduvpn-debian/tree/master/vpn-ca/debian should also work as-is in buster.
