### ISSUE TITLE
vpn-server-api-2.0.2 fails to build on Debian buster: Tests\Api\UsersModuleTest::testVerifyOtpKeyWrong fails

### ISSUE THREAD

**Issue by joostvb-gh** [eduvpn/eduvpn-debian#56]
building current  vpn-server-api-2.0.2 in a debian/buster chroot gives:

[...]
make[1]: Entering directory '/home/joostvb/git/eduvpn-debian-buster/ i/build/vpn-server-api-2.0.2'
phpab -o tests/autoload.php tests
phpab %development% - Copyright (C) 2009 - 2019 by Arne Blankerts and Contributors
Scanning directory tests
Autoload file tests/autoload.php generated.
echo "require_once 'src/autoload.php';" >> tests/autoload.php
phpunit --bootstrap=tests/autoload.php
PHPUnit 7.5.6 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.3.4-2
Configuration: /home/joostvb/git/eduvpn-debian-buster/vpn-server-api/build/vpn-server-api-2.0.2/phpunit.xml.dist
...............F.........                                         25 / 25 (100%)
Time: 108 ms, Memory: 6.00 MB
There was 1 failure:

1) LC\Server\Tests\Api\UsersModuleTest::testVerifyOtpKeyWrong
Failed asserting that true is identical to Array &0 (
    'ok' => false
    'error' => 'TOTP validation failed: invalid OTP code'
).

/home/joostvb/git/eduvpn-debian-buster/vpn-server-api/build/vpn-server-api-2.0.2/tests/Api/UsersModuleTest.php:165
FAILURES!
Tests: 25, Assertions: 28, Failures: 1.
make[1]: *** [debian/rules:21: override_dh_auto_test] Error 1
make[1]: Leaving directory '/home/joostvb/git/eduvpn-debian-buster/vpn-server-api/build/vpn-server-api-2.0.2'
make: *** [debian/rules:24: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

I'll investigate.  Hints welcome.

Bye,

Joost

**Comment by ghost** [comment]
you need to have version 0.3.x of php-fkooman-otp-verifier as well. Not 0.2.

**Comment by ghost** [comment]
But I don't understand as this is correct in eduvpn-debian/master?

**Comment by ghost** [comment]
fixed?
