### ISSUE TITLE
build scripts for buster / bionic

### ISSUE THREAD

**Issue by ghost** [eduvpn/eduvpn-debian#8]
Now the packages build on the host system instead of in a clean environment.  Update the build scripts to use something like mock but then for Debian.

Have a build script that creates a signed repository for:

- Debian 10
- Ubuntu 20.04 LTS

**Comment by joostvb-gh** [comment]
Indeed, https://github.com/eduvpn/eduvpn-debian/blob/master/build.sh could use
e.g. the pbuilder tool (
https://www.debian.org/doc/manuals/maint-guide/build.en.html#pbuilder ): it
builds the package in a dedicated fresh bare bones chroot environment.

**Comment by ghost** [comment]
That sounds really good! Ideally it would use the same tools the "official" Debian packages also use during build :)

**Comment by joostvb-gh** [comment]
Implemented in scripts le-repo_setup and le-build_all .

**Comment by ghost** [comment]
This still needs to be tested with the packages in the "stable" branch.

**Comment by ghost** [comment]
Preliminary list of requirements for the builder:

* [ ] work on clean installations of Debian 10 & Ubuntu (20.04 LTS);
* [ ] includes documentation describing how to create the repository from scratch, and how to configure a system to use the repository;
* [ ] signs the DEB packages with key;
* [ ] creates a full repository for putting on a web server;
* [ ] new versions of packages get added to the repository, so older versions remain available as well;
* [ ] builds packages in clean "chroot" (or similar) as to make sure all dependencies are properly listed;
* [ ] make sure all (build) dependencies as used by RPM spec are also specified for Debian packages;

**Comment by ghost** [comment]
Feel free to replace existing build/build_all scripts, rename folders, split the packages over multiple repositories, but at least current functionality should be retained, i.e.: it should be a drop-in replacement.

**Comment by ghost** [comment]
Above items are open for discussion of course! Maybe some things don't make sense, or there are better ways to handle it "the Debian way".

**Comment by ghost** [comment]
It would be really neat if one set of scripts could be used to build on all targets...

**Comment by ghost** [comment]
done.
