### ISSUE TITLE
allow specifying git commit for building packages

### ISSUE THREAD

**Issue by ghost** [eduvpn/eduvpn-debian#9]
now only a tag is used, but that's not really safe as tags can be changed. The RPM packages also use commits.

**Comment by ghost** [comment]
If we start using versioned tarballs that are signed with PGP this is no longer needed.

**Comment by joostvb-gh** [comment]
Indeed, publishing signed tarballs would fix this.

For Debian packages storing a keyring with the signer's public key in
debian/upstream/signing-key.asc (by running something like: gpg --armor
--export --export-options export-minimal 'fkooman' >signing-key.asc) and
committing that in the git repo used for Debian packaging would solve it.
Furthermore the pgpsigurlmangle option in debian/watch is needed; e.g.

opts="pgpsigurlmangle=s%$%.sig%"

or

opts="pgpsigurlmangle=s/$/.asc/"

.

At e.g. https://git.tuxed.net/fkooman/php-secookie/tag/?h=2.0.1 i see just

 php-secookie-2.0.1.zip
 php-secookie-2.0.1.tar.gz
 php-secookie-2.0.1.tar.xz

Could you create
https://git.tuxed.net/fkooman/php-secookie/snapshot/php-secookie-2.0.1.tar.xz.asc
, and create similar ones for the other eduvpn software?
Bye,

Joost

**Comment by ghost** [comment]
https://software.tuxed.net/php-secookie/download.html :)

**Comment by joostvb-gh** [comment]
ok, php-secookie debian/watch is now fixed: it verifies. will work on other packages soonish.

**Comment by joostvb-gh** [comment]
debian packages for

php-json-signer
php-oauth2-client
php-oauth2-server
php-openvpn-connection-manager
php-saml-ds
php-secookie
php-yubitwee

are now fixed.  now about to fix

vpn-admin-portal
vpn-lib-common
vpn-server-api
vpn-server-node
vpn-user-portal

.

**Comment by joostvb-gh** [comment]
This issue is no longer relevant; the underlying problem will get fixed cf issue nr 12.
